apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: lifeos
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
