apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: lifeos
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: lifeos-client:latest # Assuming this image is available locally
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
        env:
        - name: VITE_PROXY_TARGET
          value: "http://server-service:8000"
